name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v4


    - name: Build Docker image
      run: docker build -t devops-app ./app


    - name: Run container test
      run: |
        docker run -d -p 80:80 devops-app
        sleep 5
        curl localhost
